# Generated by Django 6.0.4 on 2026-04-16 08:41

import aline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='academic_document',
            field=models.FileField(blank=True, help_text='Academic document (PDF/DOCX, max 5MB)', null=True, upload_to=aline.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile picture (JPEG/PNG, max 2MB)', null=True, upload_to=aline.models.user_directory_path),
        ),
    ]
